window.noname_update={
	version:'1.9.105.8',
	update:'1.9.105.7',
	changeLog:[
		// '界曹休、界孙休、新鲍三娘',
		// 'bug修复',
		
		//当前版本独立更新内容：
		'更新核心版本：v1.9.105.8',
		'更新十周年UI v1.9.105.7.0.1',
		'优化修复扩展部分技能，人物',
		'其余一些bug修复',
	],
	files:[
		//'card/extra.js',
		//'card/huanlekapai.js',
		//'card/sp.js',
		//'card/standard.js',
		//'card/swd.js',
		//'card/mtg.js',
		//'card/gujian.js',
		//'card/guozhan.js',
		//'card/gwent.js',
		//'card/yunchou.js',
		//'card/zhenfa.js',
		//'card/zhulu.js',
		// 'character/diy.js',
		//'character/extra.js',
		// 'character/hearth.js',
		//'character/gujian.js',
		//'character/gwent.js',
        //'character/hearth.js',
		// 'character/mobile.js',
		//'character/mtg.js',
		//'character/old.js',
		// 'character/refresh.js',
		//'character/shenhua.js',
		// 'character/sp.js',
		// 'character/sp2.js',
		//'character/tw.js',
		//'character/standard.js',
		//'character/swd.js',
		//'character/xianjian.js',
		//'character/xinghuoliaoyuan.js',
		// 'character/yijiang.js',
		//'character/yxs.js',
		//'extension/boss/extension.js',
		//'layout/default/layout.css',
		//'layout/nova/layout.css',
		'mode/identity.js',
		//'mode/doudizhu.js',
		'mode/guozhan.js',
		// 'mode/chess.js',
		// 'mode/tafang.js',
		'mode/single.js',
		//'mode/stone.js',
		'mode/brawl.js',
		//'mode/versus.js',
		//'mode/boss.js',
		'game/game.js',
		'game/keyWords.js',
		//'game/server.js',
		//'game/NoSleep.js',
		'game/config.js',
		//'game/package.js',
		'game/asset.js',
		'game/source.js',
		//'theme/style/hp/xinglass.css',
		//'theme/style/hp/xinround.css',
		//'theme/style/hp/image/xinglass1.png',
		//'theme/style/hp/image/xinglass2.png',
		//'theme/style/hp/image/xinglass3.png',
		//'theme/style/hp/image/xinglass4.png',
		//'theme/style/hp/image/xinround1.png',
		//'theme/style/hp/image/xinround2.png',
		//'theme/style/hp/image/xinround3.png',
		//'theme/style/hp/image/xinround4.png',


		//个人扩展：
		'build/exsrc/ZJ联盟杀/extension.js',
		'build/exsrc/十六人扩展精简版/extension.js',

		//整合十周年：
		"extension/十周年UI/animation.js","extension/十周年UI/animations.css","extension/十周年UI/decadeLayout.css",
		"extension/十周年UI/content.js","extension/十周年UI/component.js","extension/十周年UI/effect.js","extension/十周年UI/dialog.css","extension/十周年UI/component.css","extension/十周年UI/effects.css","extension/十周年UI/equip.css","extension/十周年UI/eruda.js",
		"extension/十周年UI/extension.js","extension/十周年UI/icon.css","extension/十周年UI/layout.css","extension/十周年UI/card.css","extension/十周年UI/player.css","extension/十周年UI/spine.js",
		"extension/十周年UI/skill.js","extension/十周年UI/audio/game_start.mp3","extension/十周年UI/audio/kill_effect_sound.mp3","extension/十周年UI/assets/image/bg_xianding_shu.png","extension/十周年UI/assets/image/bg_xianding_qun.png","extension/十周年UI/assets/image/bg_xianding_wei.png",
		"extension/十周年UI/assets/image/bg_xianding_wu.png","extension/十周年UI/assets/image/shine.png","extension/十周年UI/assets/animation/desktop.ini","extension/十周年UI/assets/animation/effect_baguazhen.atlas","extension/十周年UI/assets/animation/effect_baguazhen.png","extension/十周年UI/assets/animation/effect_baguazhen.skel",
		"extension/十周年UI/assets/animation/effect_baiyinshizi.atlas","extension/十周年UI/assets/animation/effect_baiyinshizi.png","extension/十周年UI/assets/animation/effect_baiyinshizi.skel","extension/十周年UI/assets/animation/effect_bingliangcunduan.atlas","extension/十周年UI/assets/animation/effect_bingliangcunduan.png","extension/十周年UI/assets/animation/effect_bingliangcunduan.skel",
		"extension/十周年UI/assets/animation/effect_cixiongshuanggujian.png","extension/十周年UI/assets/animation/effect_cixiongshuanggujian.skel","extension/十周年UI/assets/animation/effect_cixiongshuanggujian.atlas","extension/十周年UI/assets/animation/effect_fangtianhuaji.skel","extension/十周年UI/assets/animation/effect_fangtianhuaji.atlas","extension/十周年UI/assets/animation/effect_guanshifu.png","extension/十周年UI/assets/animation/effect_fangtianhuaji.png",
		"extension/十周年UI/assets/animation/effect_guanshifu.skel","extension/十周年UI/assets/animation/effect_guanshifu.atlas","extension/十周年UI/assets/animation/effect_gudingdao.skel",
		"extension/十周年UI/assets/animation/effect_guohechaiqiao.atlas","extension/十周年UI/assets/animation/effect_guohechaiqiao.png","extension/十周年UI/assets/animation/effect_guohechaiqiao.skel","extension/十周年UI/assets/animation/effect_hanbingjian.atlas","extension/十周年UI/assets/animation/effect_hanbingjian.skel","extension/十周年UI/assets/animation/effect_hanbingjian.png",
		"extension/十周年UI/assets/animation/effect_gudingdao.atlas","extension/十周年UI/assets/animation/effect_heisha.atlas","extension/十周年UI/assets/animation/effect_heisha.png","extension/十周年UI/assets/animation/effect_heisha.skel","extension/十周年UI/assets/animation/effect_gudingdao.png","extension/十周年UI/assets/animation/effect_hongsha.atlas","extension/十周年UI/assets/animation/effect_hongsha.skel",
		"extension/十周年UI/assets/animation/effect_huogong.png","extension/十周年UI/assets/animation/effect_huogong.atlas","extension/十周年UI/assets/animation/effect_huosha.atlas","extension/十周年UI/assets/animation/effect_hongsha.png","extension/十周年UI/assets/animation/effect_huosha.skel",
		"extension/十周年UI/assets/animation/effect_jinhe.png","extension/十周年UI/assets/animation/effect_huogong.skel","extension/十周年UI/assets/animation/effect_jinhe.atlas","extension/十周年UI/assets/animation/effect_jisha1.atlas","extension/十周年UI/assets/animation/effect_jisha1.png","extension/十周年UI/assets/animation/effect_jisha1.skel",
		"extension/十周年UI/assets/animation/effect_jiu.atlas","extension/十周年UI/assets/animation/effect_jiu.png","extension/十周年UI/assets/animation/effect_jiu.skel","extension/十周年UI/assets/animation/effect_huosha.png","extension/十周年UI/assets/animation/effect_lebusishu.atlas","extension/十周年UI/assets/animation/effect_lebusishu.png","extension/十周年UI/assets/animation/effect_leisha.atlas","extension/十周年UI/assets/animation/effect_leisha.png","extension/十周年UI/assets/animation/effect_nanmanruqin.atlas","extension/十周年UI/assets/animation/effect_leisha.skel","extension/十周年UI/assets/animation/effect_nanmanruqin.png","extension/十周年UI/assets/animation/effect_nanmanruqin.skel",
		"extension/十周年UI/assets/animation/effect_numa.atlas","extension/十周年UI/assets/animation/effect_lebusishu.skel",
		"extension/十周年UI/assets/animation/effect_numa.png","extension/十周年UI/assets/animation/effect_numa.skel","extension/十周年UI/assets/animation/effect_nvzhuang.atlas","extension/十周年UI/assets/animation/effect_nvzhuang.png","extension/十周年UI/assets/animation/effect_qilingong.atlas","extension/十周年UI/assets/animation/effect_qilingong.png","extension/十周年UI/assets/animation/effect_qilingong.skel","extension/十周年UI/assets/animation/effect_qinggangjian.atlas","extension/十周年UI/assets/animation/effect_jinhe.skel","extension/十周年UI/assets/animation/effect_qinggangjian.png","extension/十周年UI/assets/animation/effect_qinggangjian.skel",
		"extension/十周年UI/assets/animation/effect_qinglongyanyuedao.atlas","extension/十周年UI/assets/animation/effect_qinglongyanyuedao.skel","extension/十周年UI/assets/animation/effect_nvzhuang.skel",
		"extension/十周年UI/assets/animation/effect_qinglongyanyuedao.png","extension/十周年UI/assets/animation/effect_renwangdun.skel",
		"extension/十周年UI/assets/animation/effect_renwangdun.atlas","extension/十周年UI/assets/animation/effect_shan.png","extension/十周年UI/assets/animation/effect_renwangdun.png","extension/十周年UI/assets/animation/effect_shan.skel","extension/十周年UI/assets/animation/effect_shandian.skel",
		"extension/十周年UI/assets/animation/effect_shandian.png","extension/十周年UI/assets/animation/effect_shoujidonghua.atlas","extension/十周年UI/assets/animation/effect_shoujidonghua.png","extension/十周年UI/assets/animation/effect_shoujidonghua.skel","extension/十周年UI/assets/animation/effect_shandian.atlas","extension/十周年UI/assets/animation/effect_shunshouqianyang.atlas","extension/十周年UI/assets/animation/effect_shan.atlas","extension/十周年UI/assets/animation/effect_shunshouqianyang.png","extension/十周年UI/assets/animation/effect_tao.skel","extension/十周年UI/assets/animation/effect_tao.atlas","extension/十周年UI/assets/animation/effect_taoyuanjieyi.skel","extension/十周年UI/assets/animation/effect_tengjiafangyu.atlas","extension/十周年UI/assets/animation/effect_shunshouqianyang.skel",
		"extension/十周年UI/assets/animation/effect_tengjiafangyu.png","extension/十周年UI/assets/animation/effect_tengjiafangyu.skel","extension/十周年UI/assets/animation/effect_taoyuanjieyi.png",
		"extension/十周年UI/assets/animation/effect_tengjiaranshao.atlas","extension/十周年UI/assets/animation/effect_tengjiaranshao.png","extension/十周年UI/assets/animation/effect_tengjiaranshao.skel","extension/十周年UI/assets/animation/effect_taoyuanjieyi.atlas","extension/十周年UI/assets/animation/effect_wanjianqifa.png","extension/十周年UI/assets/animation/effect_wanjianqifa.skel","extension/十周年UI/assets/animation/effect_wanjianqifa.atlas",
		"extension/十周年UI/assets/animation/effect_wufengjian.atlas","extension/十周年UI/assets/animation/effect_tao.png","extension/十周年UI/assets/animation/effect_wufengjian.skel",
		"extension/十周年UI/assets/animation/effect_wugufengdeng.atlas","extension/十周年UI/assets/animation/effect_wugufengdeng.png","extension/十周年UI/assets/animation/effect_wugufengdeng.skel","extension/十周年UI/assets/animation/effect_wuxiekeji.png","extension/十周年UI/assets/animation/effect_wuxiekeji.skel",
		"extension/十周年UI/assets/animation/effect_wuzhongshengyou.atlas","extension/十周年UI/assets/animation/effect_wufengjian.png","extension/十周年UI/assets/animation/effect_wuzhongshengyou.png","extension/十周年UI/assets/animation/effect_wuzhongshengyou.skel","extension/十周年UI/assets/animation/effect_xianding.json","extension/十周年UI/assets/animation/effect_xianding.atlas","extension/十周年UI/assets/animation/effect_yajiaoqiang.atlas","extension/十周年UI/assets/animation/effect_yajiaoqiang.png","extension/十周年UI/assets/animation/effect_xianding.png",
		"extension/十周年UI/assets/animation/effect_yajiaoqiang.skel","extension/十周年UI/assets/animation/effect_yexingyi.atlas","extension/十周年UI/assets/animation/effect_yexingyi.skel",
		"extension/十周年UI/assets/animation/effect_yinfengjia.atlas","extension/十周年UI/assets/animation/effect_yinfengjia.png","extension/十周年UI/assets/animation/effect_yexingyi.png","extension/十周年UI/assets/animation/effect_yinfengjia.skel","extension/十周年UI/assets/animation/effect_youxikaishi.atlas","extension/十周年UI/assets/animation/effect_youxikaishi.png","extension/十周年UI/assets/animation/effect_wuxiekeji.atlas","extension/十周年UI/assets/animation/effect_youxikaishi.skel",
		"extension/十周年UI/assets/animation/effect_zhangbashemao.skel","extension/十周年UI/assets/animation/effect_zhangbashemao.atlas","extension/十周年UI/assets/animation/effect_zheji.png","extension/十周年UI/assets/animation/effect_zheji.atlas","extension/十周年UI/assets/animation/effect_zhangbashemao.png","extension/十周年UI/assets/animation/effect_zhenwang.atlas","extension/十周年UI/assets/animation/effect_zheji.skel",
		"extension/十周年UI/assets/animation/effect_zhenwang.png","extension/十周年UI/assets/animation/effect_zhenwang.skel","extension/十周年UI/assets/animation/effect_zhugeliannu.atlas","extension/十周年UI/assets/animation/effect_zhiliao.atlas","extension/十周年UI/assets/animation/effect_zhugeliannu.png","extension/十周年UI/assets/animation/effect_zhiliao.png","extension/十周年UI/assets/animation/effect_zhugeliannu.skel","extension/十周年UI/assets/animation/effect_zhiliao.skel",
		"extension/十周年UI/assets/animation/effect_zhuqueyushan.atlas","extension/十周年UI/assets/animation/effect_zhuqueyushan.skel",
		"extension/十周年UI/assets/animation/effect_zhuqueyushan.png","extension/十周年UI/image/decoration/border_camp1.webp","extension/十周年UI/image/decoration/border_camp.webp","extension/十周年UI/image/decoration/border_camp3.webp","extension/十周年UI/image/decoration/border_camp5.webp",
		"extension/十周年UI/image/decoration/border_camp4.webp","extension/十周年UI/image/decoration/border_hp.webp","extension/十周年UI/image/decoration/border_hp2.webp","extension/十周年UI/image/decoration/border_camp2.webp","extension/十周年UI/image/decoration/border_hp3.webp","extension/十周年UI/image/decoration/border_hp1.webp","extension/十周年UI/image/decoration/button_disable.webp","extension/十周年UI/image/decoration/card_count.webp","extension/十周年UI/image/decoration/button.webp",
		"extension/十周年UI/image/decoration/border_hp4.webp","extension/十周年UI/image/decoration/dead_bYe.webp","extension/十周年UI/image/decoration/dead_bNei.webp","extension/十周年UI/image/decoration/dead_bZhong.webp",
		"extension/十周年UI/image/decoration/dead_cong.webp","extension/十周年UI/image/decoration/dead_bZhu.webp","extension/十周年UI/image/decoration/dead_dajiang.webp","extension/十周年UI/image/decoration/dead_boss.webp","extension/十周年UI/image/decoration/dead_dizhu.webp","extension/十周年UI/image/decoration/dead_junshi.webp",
		"extension/十周年UI/image/decoration/dead_keyjun.webp","extension/十周年UI/image/decoration/dead_key.webp","extension/十周年UI/image/decoration/dead_meng.webp","extension/十周年UI/image/decoration/dead_fan.webp","extension/十周年UI/image/decoration/dead_mingzhong.webp","extension/十周年UI/image/decoration/dead_nongmin.webp",
		"extension/十周年UI/image/decoration/dead_qunjun.webp","extension/十周年UI/image/decoration/dead_rYe.webp","extension/十周年UI/image/decoration/dead_qun.webp","extension/十周年UI/image/decoration/dead_shu.webp",
		"extension/十周年UI/image/decoration/dead_rZhong.webp","extension/十周年UI/image/decoration/dead_nei.webp","extension/十周年UI/image/decoration/dead_shujun.webp","extension/十周年UI/image/decoration/dead_wei.webp","extension/十周年UI/image/decoration/dead_rZhu.webp","extension/十周年UI/image/decoration/dead_weijun.webp","extension/十周年UI/image/decoration/dead_wujun.webp",
		"extension/十周年UI/image/decoration/dead_ye.webp","extension/十周年UI/image/decoration/dead_wu.webp","extension/十周年UI/image/decoration/dead_zhong.webp","extension/十周年UI/image/decoration/dead_zhu.webp","extension/十周年UI/image/decoration/dead_zeishou.webp","extension/十周年UI/image/decoration/dead_rNei.webp","extension/十周年UI/image/decoration/identity_boss.webp","extension/十周年UI/image/decoration/identity_bing.webp",
		"extension/十周年UI/image/decoration/identity_bYe.webp","extension/十周年UI/image/decoration/identity_bZhu.webp","extension/十周年UI/image/decoration/identity_bZhong.webp","extension/十周年UI/image/decoration/identity_bNei.webp","extension/十周年UI/image/decoration/identity_cai2.webp","extension/十周年UI/image/decoration/dialog.webp","extension/十周年UI/image/decoration/identity_cai.webp",
		"extension/十周年UI/image/decoration/identity_dajiang.webp","extension/十周年UI/image/decoration/identity_jian.webp","extension/十周年UI/image/decoration/identity_dizhu.webp","extension/十周年UI/image/decoration/identity_jiang.webp","extension/十周年UI/image/decoration/identity_fan.webp",
		"extension/十周年UI/image/decoration/identity_junshi.webp","extension/十周年UI/image/decoration/identity_cong.webp","extension/十周年UI/image/decoration/identity_mingzhong.webp","extension/十周年UI/image/decoration/identity_nongmin.webp",
		"extension/十周年UI/image/decoration/identity_meng.webp","extension/十周年UI/image/decoration/identity_nei.webp","extension/十周年UI/image/decoration/identity_rNei.webp","extension/十周年UI/image/decoration/identity_rZhong.webp","extension/十周年UI/image/decoration/identity_qun.webp","extension/十周年UI/image/decoration/identity_rZhu.webp","extension/十周年UI/image/decoration/identity_shuai.webp","extension/十周年UI/image/decoration/identity_wei.webp","extension/十周年UI/image/decoration/identity_shu.webp",
		"extension/十周年UI/image/decoration/identity_wu.webp","extension/十周年UI/image/decoration/identity_rYe.webp","extension/十周年UI/image/decoration/identity_zeishou.webp","extension/十周年UI/image/decoration/identity_zhong_false.webp","extension/十周年UI/image/decoration/identity_zhu.webp","extension/十周年UI/image/decoration/identity_zhu_false.webp","extension/十周年UI/image/decoration/identity_ye.webp","extension/十周年UI/image/decoration/name_daqin.webp","extension/十周年UI/image/decoration/identity_zu.webp","extension/十周年UI/image/decoration/name_FIRE.webp",
		"extension/十周年UI/image/decoration/name_key.webp","extension/十周年UI/image/decoration/name_GOLD.webp","extension/十周年UI/image/decoration/name_qun.webp","extension/十周年UI/image/decoration/name_NONE.webp","extension/十周年UI/image/decoration/identity_zhong.webp",
		"extension/十周年UI/image/decoration/name_shen.webp","extension/十周年UI/image/decoration/name_unknown.webp","extension/十周年UI/image/decoration/name_WATER.webp","extension/十周年UI/image/decoration/name_shu.webp",
		"extension/十周年UI/image/decoration/name_western.webp","extension/十周年UI/image/decoration/name_WOOD.webp",
		"extension/十周年UI/image/decoration/name_wei.webp","extension/十周年UI/image/decoration/name_wu.webp","extension/十周年UI/image/decoration/vs.webp","extension/十周年UI/image/decoration/name_ye.webp","extension/十周年UI/image/card/baiyin.webp","extension/十周年UI/image/card/bingliang.webp",
		"extension/十周年UI/image/card/bagua.webp","extension/十周年UI/image/card/caochuanjiejian.webp","extension/十周年UI/image/card/caochuan.webp","extension/十周年UI/image/card/chenhuodajie.webp","extension/十周年UI/image/card/chitu.webp","extension/十周年UI/image/card/caomu.webp","extension/十周年UI/image/card/chixueqingfeng.webp","extension/十周年UI/image/card/chiyanzhenhunqin.webp","extension/十周年UI/image/card/chiling.webp",
		"extension/十周年UI/image/card/dawan.webp","extension/十周年UI/image/card/cixiong.webp","extension/十周年UI/image/card/diaobingqianjiang.webp","extension/十周年UI/image/card/dilu.webp","extension/十周年UI/image/card/diaohulishan.webp",
		"extension/十周年UI/image/decoration/name_SOIL.webp","extension/十周年UI/image/card/dinglanyemingzhu.webp","extension/十周年UI/image/card/du.webp","extension/十周年UI/image/card/feilongduofeng.webp","extension/十周年UI/image/card/fudichouxin.webp","extension/十周年UI/image/card/fengchu_card.webp",
		"extension/十周年UI/image/card/fulei.webp","extension/十周年UI/image/card/guanshi.webp","extension/十周年UI/image/card/geanguanhuo.webp","extension/十周年UI/image/card/guding.webp",
		"extension/十周年UI/image/card/gubuzifeng.webp","extension/十周年UI/image/card/guilongzhanyuedao.webp","extension/十周年UI/image/card/guohe.webp","extension/十周年UI/image/card/guofengyupao.webp","extension/十周年UI/image/card/hanbing.webp","extension/十周年UI/image/card/hongmianbaihuapao.webp",
		"extension/十周年UI/image/card/hongshui.webp","extension/十周年UI/image/card/honghuangzhili.webp","extension/十周年UI/image/card/fangtian.webp","extension/十周年UI/image/card/hualiu.webp","extension/十周年UI/image/card/huogong.webp","extension/十周年UI/image/card/huoshaolianying.webp",
		"extension/十周年UI/image/card/huoshan.webp","extension/十周年UI/image/card/huxinjing.webp","extension/十周年UI/image/card/jiejia.webp","extension/十周年UI/image/card/jinchan.webp","extension/十周年UI/image/card/jingfanma.webp","extension/十周年UI/image/card/jiedao.webp","extension/十周年UI/image/card/jiu.webp","extension/十周年UI/image/card/huosha.webp","extension/十周年UI/image/card/jinwuluorigong.webp","extension/十周年UI/image/card/juechenjinge.webp","extension/十周年UI/image/card/juedou.webp","extension/十周年UI/image/card/jueying.webp",
		"extension/十周年UI/image/card/lanyinjia.webp","extension/十周年UI/image/card/kaihua.webp","extension/十周年UI/image/card/leisha.webp","extension/十周年UI/image/card/lebu.webp","extension/十周年UI/image/card/lianjunshengyan.webp","extension/十周年UI/image/card/linglongshimandai.webp","extension/十周年UI/image/card/lingsheji.webp",
		"extension/十周年UI/image/card/liulongcanjia.webp","extension/十周年UI/image/card/longfenghemingjian.webp","extension/十周年UI/image/card/lulitongxin.webp","extension/十周年UI/image/card/minguangkai.webp","extension/十周年UI/image/card/muniu.webp",
		"extension/十周年UI/image/card/ly_piliche.webp","extension/十周年UI/image/card/numa.webp","extension/十周年UI/image/card/nanman.webp","extension/十周年UI/image/card/nvzhuang.webp","extension/十周年UI/image/card/pyzhuren_club.webp","extension/十周年UI/image/card/pyzhuren_heart.webp","extension/十周年UI/image/card/pyzhuren_shandian.webp",
		"extension/十周年UI/image/card/qibaodao.webp","extension/十周年UI/image/card/pyzhuren_spade.webp","extension/十周年UI/image/card/jinhe.webp",
		"extension/十周年UI/image/card/qicaishenlu.webp","extension/十周年UI/image/card/qijia.webp",
		"extension/十周年UI/image/card/pyzhuren_diamond.webp","extension/十周年UI/image/card/qinggang.webp","extension/十周年UI/image/card/qinglong.webp","extension/十周年UI/image/card/renwang.webp","extension/十周年UI/image/card/rewrite_baiyin.webp",
		"extension/十周年UI/image/card/rewrite_bagua.webp","extension/十周年UI/image/card/rewrite_lanyinjia.webp","extension/十周年UI/image/card/rewrite_renwang.webp","extension/十周年UI/image/card/rewrite_tengjia.webp","extension/十周年UI/image/card/rewrite_zhuge.webp","extension/十周年UI/image/card/sadouchengbing.webp","extension/十周年UI/image/card/qimenbagua.webp","extension/十周年UI/image/card/shandian.webp","extension/十周年UI/image/card/sha.webp","extension/十周年UI/image/card/shan.webp","extension/十周年UI/image/card/shanrangzhaoshu.webp","extension/十周年UI/image/card/sanjian.webp",
		"extension/十周年UI/image/card/shengdong.webp","extension/十周年UI/image/card/shezhanqunru.webp","extension/十周年UI/image/card/shuijing_card.webp","extension/十周年UI/image/card/shufazijinguan.webp",
		"extension/十周年UI/image/card/shuiyanqijunx.webp","extension/十周年UI/image/card/qilin.webp","extension/十周年UI/image/card/shunshou.webp","extension/十周年UI/image/card/suolianjia.webp",
		"extension/十周年UI/image/card/taipingyaoshu.webp","extension/十周年UI/image/card/shuiyanqijun.webp","extension/十周年UI/image/card/tengjia.webp","extension/十周年UI/image/card/tiesuo.webp","extension/十周年UI/image/card/toulianghuanzhu.webp",
		"extension/十周年UI/image/card/wangmeizhike.webp","extension/十周年UI/image/card/wanjian.webp","extension/十周年UI/image/card/wolong_card.webp","extension/十周年UI/image/card/wugu.webp","extension/十周年UI/image/card/taoyuan.webp","extension/十周年UI/image/card/wufengjian.webp",
		"extension/十周年UI/image/card/wushuangfangtianji.webp","extension/十周年UI/image/card/wuliu.webp","extension/十周年UI/image/card/wuzhong.webp","extension/十周年UI/image/card/wy_meirenji.webp","extension/十周年UI/image/card/xietianzi.webp","extension/十周年UI/image/card/xingtianpojunfu.webp",
		"extension/十周年UI/image/card/wy_xiaolicangdao.webp","extension/十周年UI/image/card/xuanjian_card.webp","extension/十周年UI/image/card/xiuluolianyuji.webp","extension/十周年UI/image/card/xuwangzhimian.webp","extension/十周年UI/image/card/yajiaoqiang.webp","extension/十周年UI/image/card/yexingyi.webp",
		"extension/十周年UI/image/card/tao.webp","extension/十周年UI/image/card/wuxie.webp","extension/十周年UI/image/card/yihuajiemu.webp","extension/十周年UI/image/card/yinyueqiang.webp","extension/十周年UI/image/card/youdishenru.webp","extension/十周年UI/image/card/yiyi.webp","extension/十周年UI/image/card/yuanjiao.webp",
		"extension/十周年UI/image/card/yuxi.webp","extension/十周年UI/image/card/zheji.webp","extension/十周年UI/image/card/zengbin.webp","extension/十周年UI/image/card/zhibi.webp","extension/十周年UI/image/card/zhangba.webp","extension/十周年UI/image/card/yinfengjia.webp","extension/十周年UI/image/card/zhulu_card.webp","extension/十周年UI/image/card/zhuahuang.webp",
		"extension/十周年UI/image/card/zhungangshuo.webp","extension/十周年UI/image/card/zhuge.webp","extension/十周年UI/image/card/zhuque.webp","extension/十周年UI/image/card/zixin.webp",


		//整合未来科技：
		"extension/未来科技/extension.js",

		//zj联盟杀资源：
		
	]
};
